name: erkatoy_afex_ai
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #firebase
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3

  #network
  dio: ^5.4.1
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1

  #state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  rxdart: ^0.27.7

  #hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  path: ^1.8.3

  #di
  get_it: ^7.7.0

  #audio
  just_audio: ^0.9.39
  record: ^5.1.2

  #system
  go_router: ^14.1.0
  permission_handler: ^11.3.0
  device_info_plus: ^10.1.0
  easy_localization: ^3.0.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  #ui
  pinput: ^5.0.0
  carousel_slider: ^4.2.1
  lottie: ^3.1.0
  google_fonts: 6.2.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/png/
    - assets/images/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
